version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/public:/usr/src/app/public
      - ./backend/shop.db:/usr/src/app/shop.db
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=change_me
      - JWT_SECRET=supersecret
      - STRIPE_SECRET_KEY=sk_test_xxx
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API=http://localhost:4000
    restart: unless-stopped